services:
  postgres:
    image: postgres:17
    environment:
      POSTGRES_DB: factory_energy
      POSTGRES_USER: factory
      POSTGRES_PASSWORD: factory
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  streamlit:
    build: .
    ports:
      - "8501:8501"
    depends_on:
      - postgres

  api:
    build: .
    command: uvicorn api:app --host 0.0.0.0 --port 8000
    ports:
      - "8000:8000"
    depends_on:
      - postgres

  grafana:
    image: grafana/grafana:12.1.1
    ports:
      - "3000:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: admin
    volumes:
      - grafana_data:/var/lib/grafana
      - ./grafana/provisioning:/etc/grafana/provisioning
      - ./grafana/dashboards:/var/lib/grafana/dashboards
    depends_on:
      - postgres

volumes:
  postgres_data:
  grafana_data:
