apiVersion: 1

datasources:
  - name: Factory PostgreSQL
    type: postgres
    access: proxy
    url: postgres:5432
    user: factory
    secureJsonData:
      password: factory
    jsonData:
      database: factory_energy
      sslmode: disable
      postgresVersion: 1700
      timescaledb: false
    isDefault: true
